"""
Centralized runtime defaults for deep_think_mcp.

This module is the single source of truth for operational defaults used across
server, engine, discovery, executor, and tool invocation paths.
"""

# Policy defaults
DEFAULT_DATA_POLICY = "any"  # "any" | "local" | "cloud"

# Deep-think pass defaults/bounds
DEFAULT_DEEP_THINK_PASSES = 3
MIN_DEEP_THINK_PASSES = 2
MAX_DEEP_THINK_PASSES = 6

# Fan-out defaults/bounds
DEFAULT_FAN_OUT_WIDTH = 3
DEFAULT_FAN_OUT_HEIGHT = 2
MIN_FAN_OUT_WIDTH = 1
MAX_FAN_OUT_WIDTH = 6
MIN_FAN_OUT_HEIGHT = 1
MAX_FAN_OUT_HEIGHT = 5
DEFAULT_MAX_PARALLEL = 2
DEFAULT_MAX_WIDTH = 6
DEFAULT_CONFIDENCE_THRESHOLD = 50

# Adaptive/tool defaults
DEFAULT_ADAPTIVE_ANALYSIS_MODEL = "light"
DEFAULT_MAX_TOOL_CALLS_PER_PERSPECTIVE = 5
DEFAULT_TOOL_TIMEOUT_SECS = 10
DEFAULT_TOOL_EVIDENCE_WEIGHT = 0.7
DEFAULT_BATCH_TIMEOUT_SECS = 30

# Executor-level reasoning/tool/pass timeouts
DEFAULT_REASONING_TIMEOUT_SECS = 30
DEFAULT_PASS_TIMEOUT_SECS = 900
TASK_CLASSIFIER_TIMEOUT_SECS = 20.0
GUARDIAN_TIMEOUT_SECS = 10
OLLAMA_DISCOVERY_HTTP_TIMEOUT_SECS = 5

# Tool invocation timeout bounds
MIN_TOOL_TIMEOUT_SECS = 1
MAX_TOOL_TIMEOUT_SECS = 1800

# Discovery/model timeout defaults
DEFAULT_MODEL_TIMEOUT_SECS = 900
DISCOVERY_TIMEOUT_MIN_SECS = 135
DISCOVERY_TIMEOUT_MAX_SECS = 900
DISCOVERY_TIMEOUT_MULTIPLIER = 8.0
DEFAULT_LOCAL_TIMEOUT_SLOWDOWN = 1.5
DISCOVERY_OLLAMA_TAGS_TIMEOUT_SECS = 8

# Tool registry capability defaults
DEFAULT_WEB_SEARCH_TIMEOUT_SECS = 15
DEFAULT_CODE_SEARCH_TIMEOUT_SECS = 20
DEFAULT_DOCUMENT_FETCH_TIMEOUT_SECS = 10
DEFAULT_NOVA_SEARCH_TIMEOUT_SECS = 25
LOCAL_WEB_SEARCH_TIMEOUT_CAP_SECS = 120
LOCAL_WEB_SEARCH_FALLBACK_TIMEOUT_CAP_SECS = 60
LOCAL_CODE_SEARCH_TIMEOUT_CAP_SECS = 120
TOOL_BATCH_RESULT_GRACE_TIMEOUT_SECS = 5
CONSERVATIVE_TOOL_TIMEOUT_SECS = 20
AGGRESSIVE_TOOL_TIMEOUT_SECS = 60

# Worker lifecycle timeouts
WORKER_SHUTDOWN_TIMEOUT_SECS = 30
WORKER_CANCEL_GRACE_TIMEOUT_SECS = 2.0

# SQLite connection defaults
SQLITE_CONNECT_TIMEOUT_SECS = 10
SQLITE_BUSY_TIMEOUT_MS = 5000
